apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot3-back
  name: springboot3-back
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 9096-9096
    port: 9096
    protocol: TCP
    targetPort: 9096
  selector:
    app: springboot3-back
  type: ClusterIP
status:
  loadBalancer: {}
