apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot3-front
  name: springboot3-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot3-front
  template:
    metadata:
      labels:
        app: springboot3-front
    spec:
      containers:
      - image: springboot3-front:latest
        name: springboot3-front
        imagePullPolicy: IfNotPresent # require
        ports:
        - containerPort: 8080
          name: app
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://example-collector.monitoring.svc.cluster.local:4317"
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_SERVICE_NAME # Tempo連携時の名前
          value: "springboot3-front"
